import * as THREE from 'three';

export const CONSTANTS = {
  MOVE_SPEED_GROUND: 19,
  MOVE_SPEED_FLY: 29,
  GRAVITY: 42,
  FLY_FORCE: 23,
  SPRINT_MULTIPLIER: 1.9,
  BASE_PIGEON_HEIGHT: 3.2,
  BODY_TURN_LERP: 0.32,
  CAMERA_DISTANCE: -15.5,
  CAMERA_HEIGHT: 5.2,
  CAMERA_PITCH_MIN: -0.05,
  CAMERA_PITCH_MAX: 0.05,
  CAMERA_LERP: 0.18,
  MOUSE_SENS_PITCH: 0.0002,
  ORBIT_DISTANCE: 18,
  ORBIT_HEIGHT: 7,
  ORBIT_SENS: 0.003,
  ORBIT_PITCH_MIN: -0.35,
  ORBIT_PITCH_MAX: 0.75,
  FRICTION_GROUND: 0.87,
  FRICTION_FLY: 0.935,
  MAX_SCORE: 500,
  CITY_SIZE: 340,
  FOREST_INNER_RADIUS: 390,
  FOREST_OUTER_RADIUS: 760
};

export function createGameState() {
  return {
    scene: null,
    camera: null,
    renderer: null,
    clock: null,
    raycaster: null,
    player: null,
    wings: [],
    legs: [],
    tailFeathers: [],
    pigeonBody: null,
    pigeonHead: null,
    originalBodyColor: null,
    velocityY: 0,
    moveVelocity: new THREE.Vector3(),
    targetYaw: Math.PI,
    isFlying: false,
    isPointerLocked: false,
    gameRunning: false,
    isOrbiting: false,
    seeds: [],
    seedMaterial: null,
    worldRoot: null,
    worldGroups: null,
    buildingBoxes: [],
    cameraObstacles: [],
    tmpVecForward: new THREE.Vector3(),
    tmpVecRight: new THREE.Vector3(),
    tmpMoveDir: new THREE.Vector3(),
    tmpNewPos: new THREE.Vector3(),
    tmpAxisPos: new THREE.Vector3(),
    tmpPlayerXZ: new THREE.Vector3(),
    tmpCollisionSize: new THREE.Vector3(),
    tmpPlayerXZSize: new THREE.Vector3(),
    tmpBox: new THREE.Box3(),
    tmpPlayerXZBox: new THREE.Box3(),
    score: 0,
    timeLeft: 600,
    slowDownEndTime: 0,
    poisonEndTime: 0,
    startTime: 0,
    timerId: null,
    keys: {},
    mouseSensitivity: 0.0024,
    orbitYaw: 0,
    orbitPitch: 0,
    cameraPitch: 0.15,
    sun: null,
    sunLight: null,
    ambientLight: null,
    stars: null,
    audioContext: null,
    lastFootstepTime: 0
  };
}
